apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-sample
spec:
  template:
    spec:
      containers:
        - image: clouddeploy-cloudrun-app-image
          startupProbe:
            httpGet:
              path: "/actuator/health/readiness"
              httpHeaders:
                - name: "HOST"
                  value: "localhost:8080"
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
            httpHeaders:
              - name: "HOST"
                value: "localhost:8080"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: gcp