apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-sample
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '20'
    spec:
      containerConcurrency: 1000
      containers:
        - image: clouddeploy-cloudrun-app-image
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: "/actuator/health/readiness"
              httpHeaders:
                - name: "HOST"
                  value: "localhost:8080"
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              httpHeaders:
                - name: "HOST"
                  value: "localhost:8080"
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: gcp