apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-sample
spec:
  template:
    spec:
      containers:
      - image: clouddeploy-cloudrun-app-image
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: gcp
