apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-sample
spec:
  template:
    spec:
      containers:
      - image: clouddeploy-cloudrun-app-image
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
          initialDelaySeconds: 30
          timeoutSeconds: 10
          failureThreshold: 10
          periodSeconds: 10
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#          initialDelaySeconds: 30
#          timeoutSeconds: 10
#          failureThreshold: 10
#          periodSeconds: 10
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: gcp
