apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-sample
spec:
  template:
    spec:
      containers:
      - image: clouddeploy-cloudrun-app-image
        startupProbe:
          httpGet:
            path: "/actuator/health/readiness"
        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: gcp
