apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: clouddeploy-cloudrun-skaffold
manifests:
  kustomize:
    paths:
    - manifests/base
build:
  artifacts:
  - image: clouddeploy-cloudrun-app-image
    jib: {}
profiles:
- name: dev
  manifests:
    kustomize:
      paths:
        - manifests/overlays/dev
- name: prod
  manifests:
    kustomize:
      paths:
        - manifests/overlays/prod
deploy:
  cloudrun:
    region: us-west1-a
