spring:
  cloud:
    gcp:
      metrics:
        enabled: true
      core:
        enabled: true


management:
  metrics:
    export:
      stackdriver:
        enabled: false

logging:
  level:
    root: debug
