spring:
  cloud:
    gcp:
      metrics:
        enabled: true
      core:
        enabled: true


management:
  stackdriver:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: debug
