spring:
  cloud:
    gcp:
      metrics:
        enabled: false
      core:
        enabled: false

management:
  health:
    probes:
      enabled: true
  metrics:
    export:
      stackdriver:
        enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
